# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df51f5010700398035b104cef5749eae767103b30249cebd88f75821a373b7e8ec110622d684552aaf72dcba3ec7631d8f42dc4b88b879aab57cad4e88915750

test:
  secret_key_base: c5f161af68448b03755ce8687a3d7acaad8179b4aef51f81cd04bce9183f060122340e4da24901d89b18ed6b1645d7c5874bb365d7611777b7c15bb69177d776

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
